### ISSUE TITLE
Add Participant runs out of digits

### ISSUE THREAD

**Issue by lostcarpark** [olszowka/Zambia#100]
I made the mistake of giving my first member a badge number of 1 (actually 0001), then used the Add Participant page to create additional members.
This worked fine until I got to participant 10, but then it kept trying to add additional participants with number 10.
This is because the new participant number is generated using a SELECT MAX() on a character field, so 9 is treated as higher than 10.
I have come up with the following fix for my test site, to allow me to add additional participants:
Replace 3 lines starting at 165 in AddZambiaUser.php with the following:
```
	$prefix_len = mb_strlen(REG_PART_PREFIX) + 1;
	$query=<<<EOD
SELECT
		MAX(CONVERT(SUBSTRING(badgeid, $prefix_len), UNSIGNED)) M
```
I'm sharing in case it may be useful.

**Comment by olszowka** [comment]
Fixed by PR #104 .
