### ISSUE TITLE
Survey fields: HTML fields with illegal chars in shortname

### ISSUE THREAD

**Issue by lostcarpark** [olszowka/Zambia#127]
If you have a question mark in the "short name" of a field of type "html-text", it doesn't display the HTML editor for that field. It also doesn't display the editor for any "html-text" fields below it on the form. The affected fields just display a normal textarea. Removing the question mark from shortname makes everything go back to normal.

I'm assuming the short name gets used to create the ID of the form elements, and the rich text editor can't attach to it with the question mark. I haven't tested for other characters, but I expect it will also be caused by other illegal characters.

Simple solution is to not put question marks in short name, but users won't remember that.

I expect at some point we should make the survey editor either restrict the characters that can be entered in shortname, or make the form builder sanitise the shortname field when creating the form element IDs.

**Comment by sydwhv** [comment]
Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), U+003E GREATER-THAN SIGN (>), U+002F SOLIDUS (/), and U+003D EQUALS SIGN (=) characters, the control characters, and any characters that are not defined by Unicode. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that are an ASCII case-insensitive match for the attribute's name.

ok, question mark isn't one of those, but I guess tinyMCE can't deal with it.  The system already changes blank to _ in the field name, I guess short name should filter out " ' > < / # and ? at least.

**Comment by sydwhv** [comment]
actually, I was able to code a change for this issue changing only EditSurvey.xsl and EditSurvey.js
