### ISSUE TITLE
Provide UI for configuration

### ISSUE THREAD

**Issue by olszowka** [olszowka/Zambia#41]
This could be provided in multiple steps.  Controlling just is_current flag of Phases is a good, simple start.

**Comment by LVerhulst4321** [comment]
I've actually started a little work on this. I've created another "mode" called Administrator that will give a person with that mode access to other pages, one being to update the is_current flag of Phases.

**Comment by olszowka** [comment]
So there is already a PermissionRole and section of menu bar for Admin.
Right now the only entry there is regenerating the report menus.  I figured
the new functionality would tie into that.

Note, I think that menuing system supports submenus even though we haven't
used them, yet.

  --PeterO

**Comment by LVerhulst4321** [comment]
I want a whole separate Administrator section. That is what I am making. I think that eventually there would be too much stuff for just a menu and submenus.

**Comment by olszowka** [comment]
Do you mean comparable to staff, participant, and brainstorm?  In that
case, what would be the menu item to put user into that section?

  --PeterO

**Comment by LVerhulst4321** [comment]
Here's what I've made. I hope you can see this image.

![image](https://user-images.githubusercontent.com/25570607/68807755-01ff6b00-062e-11ea-8a9f-5ff1a885fc96.png)

**Comment by olszowka** [comment]
PR 61 is a start in this direction.  It adds a page for setting which Phases are "current".

**Comment by olszowka** [comment]
This is mostly done.  Issue #101 is all that remains.
