### ISSUE TITLE
Bad URL for "Staff Overview"

### ISSUE THREAD

**Issue by deguspice** [olszowka/Zambia#45]
"Staff Overview" on the the left side of the nav bar has a bad URL.  It wants to go to "https://StaffPage.php".  You probably want just a single '/' in `<a class="brand" href="//StaffPage.php">`

The relevant bit of HTML on https://zambia.arisia.org/StaffPage.php is

-----------------
```
<nav id="staffNav" class="navbar navbar-inverse">
--
  | <div class="navbar-inner">
  | <div class="container" style="width: auto;">
  | <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </a>
  | <a class="brand" href="//StaffPage.php">Staff Overview</a>
```
-----------------

**Comment by olszowka** [comment]
The problem is caused by the inconsistency from server to server in what is returned by the server_info() function in php.  It is not feasible to get this link to work reliably on all (or even most) servers, so the link has been removed altogether in the latest version of Zambia.
