### ISSUE TITLE
Convert DB library to mysqli

### ISSUE THREAD

**Issue by olszowka** [olszowka/Zambia#6]
Required for compatibility with PHP 7.

**Comment by LVerhulst4321** [comment]
Hi Peter. I've converted my copy of Zambia to mysqli for Capricon. Would you be interested in having me help with this on your copy on Github?

**Comment by olszowka** [comment]
Can you make a pull request of it?  I'm about 1/3 done with it--I've been
doing a lot of code cleanup while I'm doing it, so it's taking much longer
than simply replacing all the mysql functions and rearranging the function
arguments.  I'd like to keep as much of the cleanup I've done as I can.

  --PeterO

**Comment by LVerhulst4321** [comment]
Probably. I don't have much experience using Github, so a few questions. I assume the mysqli branch has the changes, correct? Do I go to that branch and click "New Pull Request"?

**Comment by olszowka** [comment]
No, you start by creating your own branch. Ideally, the branch should be
made from whatever code revision you started with.

Then you commit your branch, and then create a pull request comparing that
branch to my mysqli branch.

  --PeterO

**Comment by LVerhulst4321** [comment]
Ok. Sounds good. I also re-read the beginners guide. 
I have a convention that I am leaving for this afternoon, so I'll look at this when I get back.

**Comment by olszowka** [comment]
This is nearing completion.  Work is in mysqli branch.

**Comment by olszowka** [comment]
Closed with commit 1063744e780f2c7d0bea4e53173ccbe8f56ead58
