### ISSUE TITLE
Scheduled Sessions not displaying in Grid Scheduler

### ISSUE THREAD

**Issue by lostcarpark** [olszowka/Zambia#99]
I'm having a problem with the grid scheduler.
I can select rooms to schedule, and then select sessions and drag them on to the grid.
When I drag a session on to the grid, it gets assigned to the room and the time set, but the grid continues to show an empty square. When I reload the grid, none of the scheduled sessions appear in it.
However, when I switch to the "Maintain Room Schedule" view, and select the room, I can see the sessions have been scheduled.
I suspect this is an issue with my configuration, rather than the application itself, but I'd really appreciate any suggestions on how to diagnose the problem.

**Comment by olszowka** [comment]
Hi,

Do you ever see anything in the grid scheduler?

Which browser are you using?  Have you tried a different browser?

Can you find the Apache error log?  Is there anything relevant in there?

  --PeterO

**Comment by lostcarpark** [comment]
I'm getting the same result in both Chrome and Firefox.
I've found the webserver log, and the following error is logged when the Grid Schedular page loads:
`"PHP message: PHP Warning:  fopen(ReportMenuInclude.php): failed to open stream: No such file or directory in /var/www/vhosts/lostcarpark.com/zambia/webpages/StaffHeader.php on line 48"`
but there doesn't seem to be any error logged when the grid displays.
I will confess I'm running it on Nginx rather then Apache.

**Comment by olszowka** [comment]
That error is unrelated an just means you need to build your report menus.
It’s a menu item in the admin section if you are logged in as an admin.

I haven’t run it on nginx, but I don’t see why it shouldn’t work. The fact
that you see the other error demonstrates PHP errors are being logged.

  —PeterO

**Comment by olszowka** [comment]
Can you remove any credentials from it and send me your db_name.php file?

  --PeterO

**Comment by lostcarpark** [comment]
Thanks, Peter,
Would it be okay to email it to you?

**Comment by olszowka** [comment]
Sure.

  —PeterO

**Comment by lostcarpark** [comment]
Thanks for your help. I'm not sure how to get your email address.

**Comment by olszowka** [comment]
Note for readers--this problem was caused by misinterpretation of input field causing sessions of 30 seconds duration to be created.  Such sessions were not visible on the grid scheduler.
